name: workflow to create an Azure VM, build and run the bullhorn application through npm with node.js and angular.

on: push

env:
  AZURE_RESOURCE_GROUP: Bullhorn-DEV
  AZURE_ARM_PATH: 'https://github.com/brianveltman/bullhorn-poc/tree/master/ARM-template/template.json'
  AZURE_ARMPARA_PATH: 'https://github.com/brianveltman/bullhorn-poc/tree/master/ARM-template/parameters.json'

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.az_sp_github }},

    # - run:
    #     az group deployment create \
    #     --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
    #     --template-file ${{ env.AZURE_ARM_PATH }} \
    #     --parameters ${{ env.AZURE_ARMPARA_PATH }} 

    - name: logout
      run: |
        az logout