# This action can be used to create or update a resource group in Azure using the Azure Resource Manager templates 
# One can also use this to delete a resource group, including all the resources within the resource group.

action "Manage Azure Resources" {
  uses = "Azure/github-actions/arm@master"
  env = {
    AZURE_RESOURCE_GROUP = "<Resource Group Name"
    AZURE_TEMPLATE_LOCATION = "<URL or Relative path in your repository>"
    AZURE_TEMPLATE_PARAM_FILE = "<URL or Relative path in your repository>"
  }
  needs = ["Azure Login"]
}

# The GitHub Action for Azure Login wraps the Azure CLI's az login, allowing for Actions to log into Azure.

action "Azure Login" {
  uses = "Azure/github-actions/login@master"
  env = {
    AZURE_SUBSCRIPTION = "Subscription Name"
  }
  secrets = ["AZURE_SERVICE_APP_ID", "AZURE_SERVICE_PASSWORD", "AZURE_SERVICE_TENANT"]
}
